osx_image: xcode7.1
language: objective-c

env:
  global:
    - LANG=en_US.UTF-8

before_install:
  - brew update
  - brew install carthage || brew outdated carthage || brew upgrade carthage

install:
  - bundle install --without development --deployment --jobs=3 --retry=3
  - bundle exec pod install
  - carthage bootstrap

cache:
  directories:
  - vendor/bundle
  - Pods

script:
  - rake test

after_success:
  - bash <(curl -s https://codecov.io/bash)
