osx_image: xcode7.1
language: objective-c

env:
  global:
    - LANG=en_US.UTF-8

cache:
  - bundler
  - cocoapods

script:
  - rake test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sleep 5
